### ISSUE TITLE
"_FILE_OFFSET_BITS" redefined warning on building under Solarsi 11 sparc

### ISSUE THREAD

**Issue by payme-support** [deanproxy/dlib#2]
trying to build on Solaris 11.3 on sparc platform got warning:
`
eMail/dlib$ make
gcc -g -O2 -Wall -W -I/users/iav/eMail/dlib -I/users/iav/eMail/dlib/src -I/users/iav/eMail/dlib/include -I../include  -DHAVE_CONFIG_H  -c  src/dnet.c
In file included from src/dnet.c:14:0:
/users/iav/eMail/dlib/include/config.h:183:0: warning: "_FILE_OFFSET_BITS" redefined [enabled by default]
 #define _FILE_OFFSET_BITS 64
 ^
In file included from /usr/include/stdio.h:15:0,
                 from src/dnet.c:1:
/usr/include/sys/feature_tests.h:204:0: note: this is the location of the previous definition
 #define _FILE_OFFSET_BITS 32
 ^
`
gcc (GCC) 4.8.2
What there should be, really? 32 of 64?

**Comment by deanproxy** [comment]
This is a problem with your build environment, not a bug in the compilation of dlib.  The errors are coming from your system library header files.  Unfortunately, I do not know how to help you with this issue without knowing how your system is setup.  I would suggest searching the internet a bit and seeing if you can figure out how to avoid having that redefinition.

**Comment by payme-support** [comment]
Just to close:
```diff
diff --git a/Makefile.in b/Makefile.in
index 09556c9..6519c44 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -23,6 +23,9 @@ FILES = src/dnet.o src/dhash.o src/dlist.o src/dstrbuf.o src/dutil.o src/dvector

 .PHONY: all clean-all clean distclean install uninstall

+.c.o:
+       $(CC) $(CFLAGS) -c $*.c -o $*.o
+
 all: $(FILES)
        ar rc libdlib.a $(FILES)
```
